Remove merge
DeltaE/Canada-U.S.-ElecTrade pull request #74
Opened 2021-12-06 15:24 UTC by Kiel-SFU

2021-12-08 01:07 UTC, trevorb1 requested changes

2021-12-08 01:07 UTC, trevorb1 commented on scripts/config.py
> +    outputTechs, usaDfOut = functions.createTechnologySet(countries, techsMaster, mineTechs, rnwTechs, '../dataSources/USA_Trade.csv', False)
This may be the place to start with the tech name issue?

2021-12-08 17:12 UTC, Kiel-SFU commented on scripts/usa_data_functions.py
> +    techs, dummy = functions.createTechnologySet(countries, techsMaster, mineTechs, rnwTechs, '../dataSources/USA_Trade.csv', 0)
Yes, you're right. I included it because the original getCapToActivityUnit() function had it as a parameter, but I'll remove it.

2021-12-08 17:15 UTC, Kiel-SFU reviewed
Test

2021-12-08 17:15 UTC, Kiel-SFU commented on scripts/functions.py
> +    # OUTPUT:  dfOut = CSV datafile
Good point, fixed now.

2021-12-08 17:22 UTC, Kiel-SFU commented on scripts/usa_data_functions.py
> +    years = range(2019,2051)
Good one, I've now replaced all of the range functions.

2021-12-08 17:32 UTC, Kiel-SFU commented on scripts/functions.py
>      # PURPOSE: Merges several tech lists into 'data' so that they can be printed over
Good catch!

2021-12-18 06:39 UTC, trevorb1 requested changes

2021-12-18 06:41 UTC, trevorb1 commented
Looking good! The big thing I saw was that you linked this pr to issue #69 , but you are still referencing both `trade.csv` and `use_trade.csv` in the code? Not sure if this is just a mistake, or a misunderstanding of what the issue was asking for (which could totally be my fault for poorly wording it!)

2021-12-20 17:06 UTC, Kiel-SFU commented on omething for the break with (probably) most of Delta E Plus (including finding location)
> +[33mcommit 7290bd8eb079298293a09066bf9dba68958e9596[m[33m ([m[1;36mHEAD -> [m[1;32mremove-merge[m[33m)[m
Not sure how these files got in...

2021-12-20 17:23 UTC, Kiel-SFU commented on scripts/config.py
>      ####################################
Good catch

2021-12-21 18:51 UTC, trevorb1 requested changes

2021-12-21 18:51 UTC, trevorb1 commented on scripts/RETags.py
> +    #easier to do this one manually
Remove comment

2021-12-21 18:51 UTC, trevorb1 commented on scripts/functions.py
> +    # OUTPUT:  dfOut = fuel set dataframe
Outputs a fuel set or a tech set dataframe? Name of function and description are different

2021-12-21 18:51 UTC, trevorb1 commented on scripts/functions.py
> +def createTechDataframe(countries, techsMaster, mineTechs, rnwTechs, trnTechsCsvPath, generateInternational):
Lets be consistent with naming. This one is called createTechDataFrame, while the function above this is called createFuelSet, but their outputs are synonymous. Can you change one or the other to make them similar please, and make sure the rest in the file are similar as well ?

2021-12-21 19:01 UTC, merged