Remove regionalization
DeltaE/Canada-U.S.-ElecTrade pull request #95
Opened 2022-01-06 18:28 UTC by Kiel-SFU

2022-01-06 19:40 UTC, trevorb1 requested changes
Functionality, seemed good ! Couple of notes though: 
1. I think we should be consistent with what we are calling regions/subregions/countries (see issue #81). This was my fault from when we first wrote everything. Nothing needed for this pr, but I bumped up priority in the project board to address this issue 
2. The snakefile still references `Rationalization.xlsx` a lot. These references need to be removed
3. The  `Rationalization.xlsx` file in `/data` needs to be removed

2022-01-14 01:31 UTC, Kiel-SFU reviewed
Some very small comments before pulling, but it looks and works great on my end.

2022-01-14 01:31 UTC, Kiel-SFU commented on scripts/RETags.py
> -                    techName = 'PWR' + fuel + 'CAN' + subregion + '01'
The removal of 'CAN' here is a miss on my part, glad you caught it

2022-01-14 01:31 UTC, Kiel-SFU commented on scripts/functions.py
> +    #                     (CAN, {WS:[...], MW:[]...},)
Nitpick: You changed regions -> region in the function parameters but region -> regions in the function description! The same typo is in all of the similar functions.

2022-01-14 01:31 UTC, Kiel-SFU commented on scripts/functions.py
>          #Append lists together and write to a dataframe
"and write to a dataframe" is no longer accurate (my miss from earlier)

2022-01-14 03:18 UTC, merged